version: '3.7'

services:
  db:
    image: postgres:10.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - worker
      - beat
    links:
      - db
      - rabbitmq
      - worker
      - beat

  rabbitmq:
    image: rabbitmq:3.7.10-management
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672

  worker:
    build:
      context: .
      dockerfile: Dockerfile-celery-worker
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - .:/src

  beat:
    build:
      context: .
      dockerfile: Dockerfile-celery-beat
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - .:/src

volumes:
  postgres_data: