version: '3.7'

services:
  db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: usertool
      POSTGRES_PASSWORD: postool
      POSTGRES_DB: toolbox
    ports:
      - 5432:5432
    volumes:
      - /mnt/volume_blr1_01/postgres_data/:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:8000"
    depends_on:
      - db
      - rabbitmq
      - worker
      - beat
    links:
      - db
      - rabbitmq
      - worker
      - beat
      - redis_db

  rabbitmq:
    image: rabbitmq:3.7.10-management
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672

  worker:
    build:
      context: .
      dockerfile: Dockerfile-celery-worker
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  beat:
    build:
      context: .
      dockerfile: Dockerfile-celery-beat
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  redis_db:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: