# Generated by Django 2.0.10 on 2019-01-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scraper.TrackedChannel')),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.BigIntegerField()),
                ('comments', models.BigIntegerField()),
                ('subscribers', models.BigIntegerField()),
                ('video_count', models.IntegerField()),
                ('crawled_date', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelVideoMap',
            fields=[
                ('video_id', models.CharField(db_index=True, max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_url', models.TextField()),
                ('medium_url', models.TextField()),
                ('high_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.BigIntegerField()),
                ('likes', models.BigIntegerField()),
                ('dislikes', models.BigIntegerField()),
                ('favorites', models.BigIntegerField()),
                ('comments', models.BigIntegerField()),
                ('crawled_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.ChannelVideoMap')),
                ('duration', models.IntegerField()),
                ('keywords', models.TextField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Description')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Thumbnail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='channelvideomap',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Channel', to_field='channel_id'),
        ),
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Description'),
        ),
        migrations.AddField(
            model_name='channel',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Thumbnail'),
        ),
        migrations.AddField(
            model_name='videostats',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video'),
        ),
        migrations.AlterUniqueTogether(
            name='channelvideomap',
            unique_together={('channel', 'video_id')},
        ),
        migrations.AlterUniqueTogether(
            name='channelstats',
            unique_together={('channel', 'crawled_date')},
        ),
        migrations.AlterUniqueTogether(
            name='videostats',
            unique_together={('video', 'crawled_date')},
        ),
    ]
