# Generated by Django 2.0.10 on 2019-03-10 06:59

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('thumbnail_default_url', models.TextField(null=True)),
                ('thumbnail_medium_url', models.TextField(null=True)),
                ('thumbnail_high_url', models.TextField(null=True)),
                ('last_scraped', models.DateField(default=datetime.date.today)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scraper.TrackedChannel')),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=25)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('crawled_date', models.DateField(default=datetime.date.today)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.BigIntegerField(null=True)),
                ('comments', models.BigIntegerField(null=True)),
                ('subscribers', models.BigIntegerField(null=True)),
                ('video_count', models.IntegerField(null=True)),
                ('crawled_date', models.DateField(default=datetime.date.today)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelVideoMap',
            fields=[
                ('video_id', models.CharField(db_index=True, max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TopChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=25)),
                ('date', models.DateField(default=datetime.date.today)),
                ('frequency', models.CharField(max_length=25)),
                ('incremental', models.BigIntegerField(null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=25)),
                ('date', models.DateField(default=datetime.date.today)),
                ('frequency', models.CharField(max_length=25)),
                ('incremental', models.BigIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=25)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('crawled_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.BigIntegerField(null=True)),
                ('likes', models.BigIntegerField(null=True)),
                ('dislikes', models.BigIntegerField(null=True)),
                ('favorites', models.BigIntegerField(null=True)),
                ('comments', models.BigIntegerField(null=True)),
                ('crawled_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('thumbnail_default_url', models.TextField(null=True)),
                ('thumbnail_medium_url', models.TextField(null=True)),
                ('thumbnail_high_url', models.TextField(null=True)),
                ('last_scraped', models.DateField(default=datetime.date.today)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.ChannelVideoMap')),
                ('duration', models.IntegerField(null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='channelvideomap',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Channel', to_field='channel_id'),
        ),
        migrations.AddField(
            model_name='videostats',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video'),
        ),
        migrations.AddField(
            model_name='videohistory',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video'),
        ),
        migrations.AddField(
            model_name='topvideos',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video'),
        ),
        migrations.AlterUniqueTogether(
            name='channelvideomap',
            unique_together={('channel', 'video_id')},
        ),
        migrations.AlterUniqueTogether(
            name='channelstats',
            unique_together={('channel', 'crawled_date')},
        ),
        migrations.AlterUniqueTogether(
            name='videostats',
            unique_together={('video', 'crawled_date')},
        ),
    ]
