# Generated by Django 2.0.10 on 2019-03-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelhistory',
            name='new_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='channelhistory',
            name='old_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='videohistory',
            name='new_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='videohistory',
            name='old_value',
            field=models.TextField(null=True),
        ),
    ]
