# Generated by Django 2.0.10 on 2019-02-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.CharField(max_length=25)),
                ('incremental', models.BigIntegerField(null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.CharField(max_length=25)),
                ('incremental', models.BigIntegerField(null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
