# Generated by Django 2.0.10 on 2019-01-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Description'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='channelstats',
            name='comments',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='channelstats',
            name='subscribers',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='channelstats',
            name='video_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='channelstats',
            name='views',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='default_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='high_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='medium_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='videostats',
            name='comments',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videostats',
            name='crawled_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videostats',
            name='dislikes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videostats',
            name='favorites',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videostats',
            name='likes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videostats',
            name='views',
            field=models.BigIntegerField(null=True),
        ),
    ]
