# Generated by Django 2.0.10 on 2019-03-13 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190312_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_discovery',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
