# Generated by Django 2.0.10 on 2019-02-02 13:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190202_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), null=True, size=None),
        ),
    ]
