# Generated by Django 2.0.10 on 2019-01-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedChannel',
            fields=[
                ('channel_id', models.CharField(db_index=True, max_length=24, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
