# Generated by Django 2.0.10 on 2019-03-10 07:43

from django.db import migrations
import csv

def add_tracked_channels(apps, schema_editor):
    TrackedChannel = apps.get_model('scraper', 'TrackedChannel')

    with open('channel_start.csv') as csv_file:
    	csv_reader = csv.DictReader(csv_file)
    	for row in csv_reader:
    		TrackedChannel.objects.create(channel_id=row['channel_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(add_tracked_channels),
    ]
